### ISSUE TITLE
[enhancement] Handle multiple deployments to dev more gracefully

### ISSUE THREAD

**Issue by ifrost** [grafana/profiles-drilldown#440]
### Feature description

When merging a PR to main while main is still building it may cause deployment workflow to fail for one or the other PR. As the effect we may end up in lastest main not being deployed to dev.

A GitHub action finishes but the Argo Workflow is still running. If there's another Argo workflow triggered during deployment it fails and may cause that the latest main is not being deployed to dev. Unfortunately we don't have the feedback when Argo workflow finishes but we can queue GitHub actions in main to avoid clashes.

**Describe the solution you'd like**

Ideally deployments should be queued and not conflicting with each other.

Possibly we can use:

```
on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}  # ensures workflows in the same branch are grouped together
  cancel-in-progress: false # ensures workflows do not cancel each other, they will queue instead
```

### Alternatives considered

**Describe alternatives you've considered**

Please check https://docs.github.com/en/enterprise-cloud@latest/actions/writing-workflows/choosing-what-your-workflow-does/control-the-concurrency-of-workflows-and-jobs
